services:
  - type: web
    name: naa-k0
    runtime: python
    pythonVersion: 3.11.6
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: naa-k0-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

